### ISSUE TITLE
When does the Controller sample normal_arc and reduce_arc?

### ISSUE THREAD

**Issue by flymark2010** [melodyguan/enas#19]
Hi, thanks for your work. I find that the controller will sample normal_arc and reduce_arc for every child step in your code, is that right? Can you explain why? Do you try to use a sampled normal_arc and reduce_arc to train child model for a few steps, and then sampling a new normal_arc and reduce_arc?

**Comment by hyhieu** [comment]
Hi, thanks for your interest.

The controller will sample normal_arc and reduce_arc for every child step in your code because that's how it updates the shared parameters among the child models (see Section 2.2 in [our paper](https://arxiv.org/pdf/1802.03268.pdf)).

We briefly tried using the same sampled normal_arc and reduce_arc for a few steps but didn't investigate it too much, since 1 step works. We suspect that it will lead to the similar effect with training using a larger batch_size.
