### ISSUE TITLE
Why using a auxiliary heads?

### ISSUE THREAD

**Issue by flymark2010** [melodyguan/enas#22]
Why do you use a auxiliary heads? Does that affect the performance much?

**Comment by hyhieu** [comment]
We use the auxiliary heads because we follow the design of [Zoph et al (2018)](https://arxiv.org/abs/1707.07012). It helps with the performance in the first few versions of our experiments, but since then we just sticked with using the aux heads and never bothered doing an ablation study so we cannot quantify how much does it help.
